name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - setuptools
  - sphinx-rtd-theme
  - pip
  - pip:
    - sphinx-tabs
  - numpy<2.0
  - astropy
  - matplotlib
  - pandas
  - scipy